spring.application.name=reviewforge-backend

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/reviewforge
spring.datasource.username=postgres
spring.datasource.password=hari123

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=7f8e9d1c2b3a4f5e6d7c8b9a0e1f2d3c4b5a6d7e8f9a0b1c
jwt.expiration=86400000